name: Colin Chang
description: Colin Chang's blog and project repository
url: https://colinchang.org
safe: true #Github Pages overrides lsi to safe
lsi: false #Github pages overrides lsi to false

paginate: 5
paginate_path: "/page:num"
gems: [jekyll-paginate]
